Build Improvements
OpenCHAMI/smd pull request #40
Opened 2024-10-29 16:35 UTC by alexlovelltroy

* Simpler multiarch builds
* use AMD64 v4 rather than v1
* Add packages, rpm, deb, apk
* Simplify Dockerfile
* Improve clarity of Github actions

2024-11-07 02:07 UTC, synackd requested changes
Besides my comment, this builds fine. But before we merge, we'll want to correct the `--skip-publish` to `--skip publish` in the `goreleaser` command in the README.

2024-11-07 22:57 UTC, alexlovelltroy commented on Dockerfile
> +    && apk add --no-cache curl tini \
I thought docker included it natively, but that we can't count on it with all runtimes.  Do you have documentation otherwise?

2024-11-07 23:19 UTC, njones-lanl commented on Dockerfile
> +    && apk add --no-cache curl tini \
podman via: https://docs.podman.io/en/v5.2.2/markdown/podman-run.1.html#init
kubernetes I'm not actually sure off of the top of my head, but I'd presume the various CRI's have ways to handle it

2024-11-08 13:51 UTC, alexlovelltroy commented on .goreleaser.yaml
> +            - src: dist/smd_{{ .Os }}_{{ if eq .Arch "amd64" }}{{ .Arch }}_{{ .Amd64 }}{{ else }}{{ .Arch }}{{ end }}/smd
This behavior is part of the upgrade from goreleaser 2.2 to 2.4. I've updated the version in the .goreleaser.yaml to reflect the need for the newer version.

2024-11-14 16:09 UTC, synackd approved these changes
Yep, looks good to me and am able to build/run the container (tested on amd64).

2024-11-14 16:12 UTC, merged